spring.application.name=sv-repairman-requests

# Server
server.port=8081

# MySQL Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sv_truck_oil_server?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.docker.compose.enabled=false

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Session
server.servlet.session.cookie.persistent=true

# JWT
jwt.secret=0123456789ABCDEF0123456789ABCDEF
jwt.expiration=86400000

# MVC
spring.mvc.hiddenmethod.filter.enabled=true

# Multipart (File Upload)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true

# File upload directory
# server
# file.upload-dir=/sv_truck_fats/uploads
# local
file.upload-dir=uploads/

